### ISSUE TITLE
BM: Redner Inspector

### ISSUE THREAD

**Issue by TheItCrOw** [TheItCrOw/Bundestags-Mine#17]
Ein Modal, was einen Redner genauer untersucht bzw. erläutert mit Reden, Kommentare etc.

Was ich morgen angehen muss:

- [x] Laden der Reden, Kommetare etc. auf Knopfdruck und auch paginated probably... mal sehen.

**Comment by TheItCrOw** [comment]
## Stand
Soweit erstmal fertig. Siehe Screenshot

![Image](https://user-images.githubusercontent.com/49918134/188905439-d0f02497-35fe-496e-b9ff-c20b619a3a32.png)

## ToDo:
Einfügen des Modals in andere Ansichten

- [x] Themen Analyse (Alle Stellen)
- [x] Themen-Landkarte

- [x] Erweitern mit Suche und Schließbarer Animation
