### ISSUE TITLE
BM: Console-Application für Synchronisierungsaufgaben.

### ISSUE THREAD

**Issue by TheItCrOw** [TheItCrOw/Bundestags-Mine#3]
## SOLL
Wir brauchen ein Pendant zum Issue "NLP: 1) Automatisierten Einpflegen neuer Protokolle" auf der C# Seite (Am Besten das Issue vor diesem mal durchlesen). Wenn der NLP-Service neue Protokolle gefetched, analysiert und gespeichert hat, müssen wir dazu noch weitere Dinge (TOP, Abstimmungen, und weiteres) fetchen. Das soll am Besten auch automatisch passieren.

## IST
Der Code für das Ganze existiert bereits in einer Console-App in der BundestagsMine Solution: **BundestagsMine.Synchronisation**.  Dort gibt es die BundestagScraper Klasse, die TOP und Abstimmungen bereits fetched.

## ToDo

- [x] Wenn ein neues Protokoll vom NLP-Service in die DB gelangt, muss der Service hier das rallen und seine Aufgaben starten
Danach muss folgendes passieren.
- [x] Importieren neuer TOP zu dem Protokoll. Das geht grade schon automatisch in der ExportAndImportTagesordnungspunkte() Methode.
- [x] Importieren neuer Abstimmungslisten. Das ist etwas tricky: Die Abstimmungslisten werden grade von der Bundestags-Seite runtergeladen, auf der Festplatte gespeichert und dann mit einem Excel-Import (Denn die Listen sind xls Dateien) wieder in die DB importiert. Auch hierfür steht der gesamte Code - es geht hier ums zusammenfügen und Konzeption.
Für die folgenden Punkte am Besten mich fragen, dann erklär ich nochmal, was gemeint ist.
- [x] Das aktuelle Jahr (2022) muss für die Themen-Landkarte neu berechnet werden. 
- [x] Für das Themen-Rennen müssen die neuen Monate berechnet werden
- [x] Kommentar-Netzwerk müssen die neuen Kommentare berechnet werden.

## Ablauf
Zusammengefasst muss der Service:

1. Checken, wenn ein neues Protokoll vom NLP-Service kommt
2. TOP, Abstimmungen importieren.
3. Vorberechnete Datensätze (Themen-Landkarte, Rennen, Netzwerk) müssen weiter/neu berechnet werden.
4. Repeat.

**Comment by TheItCrOw** [comment]
![Image](https://user-images.githubusercontent.com/49918134/183854778-045c5d50-ed7f-4292-b180-26d4f4eb06db.png)

Wenn du sowas in deinem eigenen Projekt-Code liest, bist echt fucked XD

**Comment by TheItCrOw** [comment]
## Stand
Grade eben das erste neue Protokoll importiert mit TOP. Es fehlt noch Abstimmungslisten und die Neuberechnug mancher Objekte. Bisher siehts aber gut aus.

**Comment by TheItCrOw** [comment]
War eigentlich schon fertig, aber wies halt so ist musste ich das Berechnen des Kommentar-Netzwerks neu schreiben, weil ich das damals nur in Java gemacht habe - dann ist mir dabei aufgefallen dass ich beim Importieren der alten Daten aus der MongoDB die Annotationen für die Shouts vergessen habe... Also fehlen jetzt die Sentiment Werte für die Shouts, was beim Kommentar-Netzwerk natürlich auffällt. 

- [x] Shout Results nachziehen
- [x] Kommentar-Netzwerk berechnen fertig schreiben

**Comment by TheItCrOw** [comment]
Weiteres Problem: Der Sentiment Wert der Shouts wird (glaube ich) nicht richtig berechnet. Der ist legit immer bei 0.0, was eig. nicht sein kann... 

Muss schauen warum hier der Sentiment Wert so fucked ist.

**Comment by TheItCrOw** [comment]
Nvm, sieht doch gut aus. Es sind nur viele Sentiment 0.0 weil die Shouts oft einfach "Applaudieren" sind oder sowas.

**Comment by TheItCrOw** [comment]
## Erster Lauf
Grade einen ersten Test-Synch auf ner Test-DB gestartet. Es hat soweit alles funktioniert, aber folgende Fehler hab ich jetzt:

- [x] Die Reden in der Text-Analyse laden nicht (ShoutId bei Annotations?)
- [x] Annotations laden generell nicht (Themen-Analyse und Karte)
- [x] Network Data berechnen null reference beim synchen
- [x] Ein Excel Import error, der aber glaub normal ist.
